Repository robot-lab/judyst-link-analysis, pull requests merged in 2018-10, with the labels that each got.

#26 Solut some issues
  .gitignore
  Core/FirstAnalysis.py
  Core/api_module.py
  Core/final_analysis.py
  Core/law.py
  Core/moduleApi.py
  Core/rough_analysis.py
  Core/visualizer.py
  Core/web_crawler.py
Labels: architecture, bug, enhancement, wontfix

#30 Date format seted on day.month.year
  Core/api_module.py
Labels: bug

#32 Add realization for start_process_with method
  Core/api_module.py
Labels: Feature

#39 Fixing parsing rough links
  Core/api_module.py
  Core/final_analysis.py
  Core/rough_analysis.py
Labels: bug

#40 added replacing spaces in document numbers
  Core/rough_analysis.py
  Core/web_crawler.py
Labels: bug

#42 fixing bug with parsing date in api_module.get_headers_between_dates()
  Core/api_module.py
Labels: bug

#43 added weight to edges
  Core/api_module.py
  Core/final_analysis.py
  Core/visualizer.py
Labels: Feature, Task

#70 Moving to object architecture
  Architecture schemes.pdf
  Architecture schemes.vsdx
  link_analysis/models.py
  requirements-dev.txt
  requirements.txt
Labels: priority 1

#72 Moving to object architecture
  link_analysis/models.py
Labels: code maintenance

#82 Modules rewriting using classes
  .gitignore
  link_analysis/__init__.py
  link_analysis/__main__.py
  link_analysis/api_module.py
  link_analysis/converters.py
  link_analysis/final_analysis.py
  link_analysis/models.py
  link_analysis/rough_analysis.py
Labels: priority/top, type/code maintenance

#93 Mehchanges
  .gitignore
  dist/link_analysis-0.1-py3-none-any.whl
  dist/link_analysis-0.1.tar.gz
  link_analysis/api_module.py
  link_analysis/converters.py
  link_analysis/final_analysis.py
  link_analysis/models.py
  link_analysis/rough_analysis.py
Labels: type/feature

#97 Стабильная версия с фичей контекста, подготовленная к расширению
  dist/link_analysis-0.1-py3-none-any.whl
  dist/link_analysis-0.1.tar.gz
  link_analysis/__init__.py
  link_analysis/api_module.py
  link_analysis/converters.py
  link_analysis/final_analysis.py
  link_analysis/link_handler.py
  link_analysis/models.py
  link_analysis/rough_analysis.py
  link_analysis/wc_interface.py
Labels: type/code maintenance

#98 Небольшие фиксы
  link_analysis/api_module.py
  link_analysis/link_handler.py
  link_analysis/wc_interface.py
Labels: type/code maintenance
